# Generated by Django 6.0.2 on 2026-03-19 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0003_spacedrevision'),
        ('public_quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicattempt',
            options={'ordering': ['-completed_at']},
        ),
        migrations.AlterModelOptions(
            name='publicquiz',
            options={'ordering': ['-created_at'], 'verbose_name': 'Public Quiz', 'verbose_name_plural': 'Public Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='publicquizquestion',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='publicattempt',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publicattempt',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='publicattempt',
            name='wrong_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publicquizquestion',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of question in quiz'),
        ),
        migrations.AlterField(
            model_name='publicanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='public_quiz.publicattempt'),
        ),
        migrations.AlterField(
            model_name='publicanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publicanswer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mcq.choice'),
        ),
        migrations.AlterField(
            model_name='publicattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='public_quiz.publicquiz'),
        ),
        migrations.AlterField(
            model_name='publicattempt',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='publicquizquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_quizzes', to='mcq.question'),
        ),
        migrations.AlterField(
            model_name='publicquizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='public_quiz.publicquiz'),
        ),
        migrations.AlterUniqueTogether(
            name='publicquizquestion',
            unique_together={('quiz', 'question')},
        ),
    ]
