# Generated by Django 6.0.2 on 2026-03-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_quiz', '0002_alter_publicattempt_options_alter_publicquiz_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicquiz',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Scheduled end time for the quiz', null=True),
        ),
        migrations.AddField(
            model_name='publicquiz',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Scheduled start time for the quiz', null=True),
        ),
        migrations.AddField(
            model_name='publicquiz',
            name='time_limit',
            field=models.PositiveIntegerField(default=30, help_text='Time limit in minutes for the entire quiz'),
        ),
    ]
